### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by ZweiBR** [OneEyeBlack/NSPackBuilder#2]
There are 3 files missing for the package to work, they are:
payload
boot.dat
boot

https://a.imagem.app/otW7Kl.jpeg

**Comment by OneEyeBlack** [comment]
This program crate a package that won’t need thoses files. 
This files that you mentioned is used to Kefir package.

**Comment by ZweiBR** [comment]
> This program crate a package that won’t need thoses files. This files that you mentioned is used to Kefir package.



> This program crate a package that won’t need thoses files. This files that you mentioned is used to Kefir package.

Here it doesn't work without these files using your program

**Comment by OneEyeBlack** [comment]
Did you erase all files on SD before copy the package?
