### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by ZweiBR** [OneEyeBlack/NSPackBuilder#4]
As I said previously, it doesn't work without the files I showed before.

boot.dat
boot.ini
payload.bin

As soon as I turn on the switch it shows an error:
Missing payload.bin file

Edit:
Thank you for being able to adjust the program size for small screens xD

**Comment by OneEyeBlack** [comment]
Delete ALL folder that you have. 
Just keep the emuMMC.
Delete everything also.
And then, create your pack.
Will work.

**Comment by ZweiBR** [comment]
> Mark the option: "ERASE SDcard before copy"
> 
> Delete ALL folder that you have. Just keep the emuMMC. Delete everything also. And then, create your pack. Will work.

I'll test it, thanks
Another thing, what is the Noexes module for?

**Comment by OneEyeBlack** [comment]
It's part of Edizon homebrew.
But the function, I don't know.

**Comment by OneEyeBlack** [comment]
Let me know if works for you.
But selecting the option "ERASE SDcard before copy" will work.

**Comment by ZweiBR** [comment]
> payload.bin

I tested it now and it doesn't work without the payload.bin file.
It says the payload.bin file is missing
Tested on Switch OLED with Hwfly chip

**Comment by OneEyeBlack** [comment]
You're doing something wrong. 
Is your emuMMC file or partition?

**Comment by ZweiBR** [comment]
emuMMC is sdfiles

**Comment by OneEyeBlack** [comment]
Was you using Kefir, right?
Put your SD inside pc and delete everything on it.
Leave only your emuMMc folder there.
Open this program.
check the optin: Copy Pack to Drive > Select your SD drive > Start.
When finished, get your SD back to Switch and try.

No one get problem with this program. You're the only one...  ;)

**Comment by OneEyeBlack** [comment]
Try and let me know if works for you.

Mark the options:
- Copy Pack to Drive
- Erase SDcard before start copy

**Comment by ZweiBR** [comment]
> I may found the problem with you. I'll fix it and then you try again on next release... ok?

now it works fine, thanks

**Comment by OneEyeBlack** [comment]
Great.
**Thanks for your help.**
;)
