### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by AndersonTorres** [OneEyeBlack/NSPackBuilder#5]
Hello!
Do you have plans to release the source code of this app?

**Comment by OneEyeBlack** [comment]
Hi, mr. Anderson.
Not at present moment.
Why?

**Comment by AndersonTorres** [comment]
Mostly because my main machine is Linux, and also I like to compile and build from sources when possible.
(Even in the case of being a Windows-only app, the source code can still be useful to learn and write to other platforms.)
